### ISSUE TITLE
Simplify logic of the pipelines

### ISSUE THREAD

**Issue by jhsiao999** [stephenslab/dsc-log-fold-change#8]
Subject: `pipe_null` and `pipe_power`
Goal: simply the logic so that these two pipelines call the same score modules

Curent version
```
  define:
    data: data_poisthin_null, data_poisthin_power
    method: t_test, wilcoxon
    score: type_one_error, pval_adj, fdr, auc
  run:
    pipe_null: data_poisthin_null * method * type_one_error
    pipe_power: data_poisthin_power * method * pval_adj * (fdr * auc)
```

This is the first idea I tried but I got errors...
```
  define:
    data: data_poisthin_null, data_poisthin_power
    method: t_test, wilcoxon
    score: type_one_error, pval_adj * (fdr, auc)
  run:
    pipe_null: data_poisthin_null * method * score
    pipe_power: data_poisthin_power * method * score
```

**Comment by gaow** [comment]
The first question is whether or not we should support this:

```
    score: type_one_error, pval_adj * (fdr, auc)
```

Currently we support either mini-pipeline via `*`:

```
define: 
   score: pval_adj * fdr
```

or module groups:

```
score: fdr, auc
```

but not mixing them up like your case (in which case I should make sure we report the error properly). Secondly, are you sure you want to run all scores for both `null` and `power` pipelines?

**Comment by stephens999** [comment]
calling them null and power might be a bad idea...

basically null is a special case where you can't compute power..
but "power" could be used also to do other assessments (eg type I error on
the
subset of nulls).

I suggested running all scores in all cases  -- rather than treating the
null simulations
as a special case -- might simplify things ... but maybe not. I'm open to
disagreement on that.

**Comment by stephens999** [comment]
so is this valid?

score: type_one_error, pval_adj * fdr, pval_adj * auc

**Comment by gaow** [comment]
@stephens999 the syntax is valid as with current DSC implementation. But it is mixing up module groups and mini-pipelines. The current behavior of DSC is that when it sees `*` it will understand the entire "definition" as mini-pipelines not module groups, because a single module is also a mini-pipeline ... then recall that we have agreed to not support query on mini-pipelines due to ambiguous behavior, then the `score` definition will not be supported in query. This is why @jhsiao999 had the issue. I was thinking if I should try to detect such pattern and quite on error. But I'm thinking maybe sometimes having mini-pipeline containing a single module can be desired behavior, so I am not planning to change anything.

**Comment by stephens999** [comment]
i think we should definitely discuss. I'm not sure we have agreed on
definition of "mini-pipeline" as a concept? (but i might be misremembering).

Here is an example from the documentation

run: simulate * (winsorize * mean, mean) * score

this kind of example makes me (and perhaps other users) expect that arbitrary
combinations are possible... it is not clear to me why this is allowed but not

 score: type_one_error, pval_adj * (fdr, auc)

**Comment by gaow** [comment]
>  it is not clear to me why this is allowed but not `score: type_one_error, pval_adj * (fdr, auc)`

`score: type_one_error, pval_adj * (fdr, auc)` is indeed valid DSC syntax. In other words, benchmark with this syntax will work, for example:

```yml
a: R()
  n: 1
  $m: 2

d(a):
  n: 3

b: R()
  n: 2
  $m: 1

c: R()
  m: $m
  $n: 1

DSC:
  define:
    score: d, (a,b)*c
  run: score
```

this is going to work:

```
[GW] dsc test.dsc
INFO: DSC script exported to test.html
INFO: Constructing DSC from test.dsc ...
INFO: Building execution graph & running DSC ...
[###########] 11 steps processed (11 jobs completed)
INFO: Building DSC database ...
INFO: DSC complete!
INFO: Elapsed time 3.482 seconds.
```

What's not supported is the module group `score` in `dscquery`, because `pval_adj * (fdr, auc)` is not a module group, but is what I just referred to as "mini-pipeline". 

Let me remind ourselves why we cannot query on "mini-pipelines". For example:

```yml
a:
  n: 1
  $m: n

b:
  m: $m
  n: m
```

Then if we call it a group `score: a * b` we will not know what `score.n` refers to. Does it clarify it a bit?

**Comment by stephens999** [comment]
thanks @gaow ! Indeed this helps a lot.

Some questions:

1. Earlier you said "The first question is whether or not we should support this:
score: type_one_error, pval_adj * (fdr, auc)
"
But as I understand now this is indeed already supported (but score is not queriable).
Correct?

 @jhsiao999  can you confirm that when you said you "got errors" you meant on query? (not at runtime of dsc?)

2. @gaow said "Currently we support either mini-pipeline via *:
define: 
   score: pval_adj * fdr
"

Do you mean we support query on score in such situation? This seems to contradict what
you said above...

3. Can we agree on the terminology? I suggest "simple module" when we want to emphasise we are talking about a single module and not a compound of multiple modules (because although technically compounding
multiple modules is a pipeline, in practice one might think of pval_adj * fdr as a "compound module")
And then a  "simple group" is a group that
contains only simple modules.

**Comment by gaow** [comment]
> But as I understand now this is indeed already supported (but score is not queriable).

Yes I meant to "unsupport" it by trying to detect such user pattern and throw errors or warnings at run time of dsc command, because it will causes confusions down the line to at least our own colleagues. But technically `type_one_error` is a special case of compound module; and bad group definition in DSC file can always be salvaged via dynamic grouping at query time. So maybe documenting it with the proper terminology is the most obvious way out? 

> Do you mean we support query on score in such situation?

Sorry no. I wanted to say that in our design we meant to encourage users to stick to either module groups, or compound modules, in  `DSC::define`, but not mixing up these concepts. But you seems to suggest (see below) that the concepts can be justified with better terminology.

> Can we agree on the terminology? 

Very much happy to do so. I'm cool with compound module. Then `score: type_one_error, pval_adj * (fdr, auc)` is compound group. And dscquery only works on simple module or simple groups. It seems to have clarified it!

**Comment by stephens999** [comment]
thanks @gaow that is much clearer.

@jhsiao999 I'm thinking to streamline the benchmark logic by:
simulate -> analyze -> pval_adj -> score

where you could either have one score module that computes all your metrics
(eg type I error, power, fdr, auc, etc)
or you could have a separate module for each

there is some redundancy in this design.. because pval_adj only impacts
some scores (and some scores
only relevant for non-null data). But it definitely
simplifies the flow...

Matthew

**Comment by jhsiao999** [comment]
Thanks @gaow @stephens999 for the great discussion here!

To my understanding, these are the things that've been discussed so far:
1. Define simple module and compound module: simple module is the smallest unit of `dsc` modules, compound module combines two or more dsc modules. For example, `a` and `b are simple modules. `(a*b)` is a compound module. `(a,b)` is a pipeline of two simple modules.

2. How and if `dsc` supports compound modules:
- Yes.
- This supported: `score: type_one_error, pval_adj * fdr, pval_adj * auc` 
- This not supported: `score: type_one_error, pval_adj * (fdr,  auc)` 

3. How and if `dscquery` supports compound modules:
- No. And I learned this the hard way...


Back to my original problem @stephens999 ,`dsc` threw me an error and stopped running. I had mis-specified compound modules in the script. This was not an error while running `dsc-query`.

For future reference, below I lay out three versions of `dsc` scripts that I've gone through so far, including current working version (__Case 3__). 

__Version 1__: original problem
```
DSC:
  define:
    data: data_poisthin_null, data_poisthin_power
    method: edger, deseq2
    score: type_one_error, pval_adj * ( fdr, auc) #( fdr, auc) not suported
  run:
    pipe_null: data_poisthin_null * method * score
    pipe_power: data_poisthin_power * method * score
```


__Version 2__: `dsc` ran without error, and all data instances generated correctly. But, I ran into issues when trying to extract results. `dscquery` didn't recognize the compound modules.
```
DSC:
  define:
    data: data_poisthin_null, data_poisthin_power
    method: edger, deseq2
    score: type_one_error, pval_adj, fdr, auc
  run:
    pipe_null: data_poisthin_null * method * type_one_error
    pipe_power: data_poisthin_power * method * pval_adj *(fdr, auc)
```

__Version 3__: Thanks for Matthew's suggestion. The current version is much more simplified. The key is recognizing that 100% null gene case is a special case, and instances from this case can have `auc` and `fdr` NA values. In addition, I simplified the data modules to one and used the `prop_null` pipeline variable to generate 100% null and 90% null gene case. 

```
DSC:
  define:
    data: data_poisthin
    method: edger, deseq2
    pval_rank: pval_adj
    score: type_one_error, fdr, auc
  run:
    pipe_de: data_poisthin * method * pval_rank * score
```

Joyce

**Comment by stephens999** [comment]
On Fri, Feb 22, 2019, 19:39 Chiaowen Joyce Hsiao <notifications@github.com>
wrote:

> Thanks @gaow <https://github.com/gaow> @stephens999
> <https://github.com/stephens999> for the great discussion here!
>
> To my understanding, these are the things that've been discussed so far:
>
>    1.
>
>    Define simple module and compound module: simple module is the
>    smallest unit of dsc modules, compound module combines two or more dsc
>    modules. For example, a and b are simple modules. (a*b)is a compound
>    module.(a,b)` is a pipeline of two simple modules.
>    2.
>
>    How and if dsc supports compound modules:
>
>
>    - Yes.
>    - This supported: score: type_one_error, pval_adj * fdr, pval_adj * auc
>    - This not supported: score: type_one_error, pval_adj * (fdr, auc)
>
> I think this last is supported according to @gaow just not in query. So if
it produces error in DSC maybe we should check?

Matthew

**Comment by stephens999** [comment]
On Fri, Feb 22, 2019, 19:39 Chiaowen Joyce Hsiao <notifications@github.com>
wrote:

> Thanks @gaow <https://github.com/gaow> @stephens999
> <https://github.com/stephens999> for the great discussion here!
>
> To my understanding, these are the things that've been discussed so far:
>
>    1.
>
>    Define simple module and compound module: simple module is the
>    smallest unit of dsc modules, compound module combines two or more dsc
>    modules. For example, a and b are simple modules. (a*b)is a compound
>    module.(a,b)` is a pipeline of two simple modules.
>
> If a and b are simple modules then (a,b) is a simple group of modules....
Not a pipeline

**Comment by gaow** [comment]
> This not supported: `score: type_one_error, pval_adj * (fdr, auc)`

This should not trigger error message in `dsc` runs. I cannot reproduce an erroneous behavior with example below:

```yml
type_one_error: R()
  $q: 1

pval_adj: R()
  $p: 1

fdr: R()
   p: $p
   $q: 1

auc: R()
   p: $p
   $q: 1

DSC:
  define: 
    score:  type_one_error, pval_adj * (fdr, auc)
  run: score
```

```
$ dsc test.dsc
INFO: DSC script exported to test.html
INFO: Constructing DSC from test.dsc ...
INFO: Building execution graph & running DSC ...
[#########] 9 steps processed (9 jobs completed)
INFO: Building DSC database ...
INFO: DSC complete!
INFO: Elapsed time 5.213 seconds.
```

@jhsiao999 what's your error message exactly? Possibly something else is wrong if it indeed does not work for you? It would be helpful to proivde an example to reproduce it; or at least the error message itself. I'm happy to debug it for you via slack if there is an issue you find better to work with me interactively
